language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - PYLINT=1.9.2
  - PYLINT=1.9.3
  - PYLINT=2.0.0
  - PYLINT=2.1.1
  - PYLINT=2.2.2
  - PYLINT=master
install:
  - |
    pip install coverage coveralls
    if [ "$PYLINT" == "master" ]; then
        pip install https://github.com/PyCQA/astroid/zipball/master
        pip install https://github.com/PyCQA/pylint/zipball/master
    else
        pip install pylint==$PYLINT
    fi

script:
  - coverage run tests.py
after_success:
  - coveralls
